# Generated by Django 3.2 on 2022-12-04 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_division_parent"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="division",
            table="Division",
        ),
        migrations.AlterModelTable(
            name="employer",
            table="Employer",
        ),
        migrations.AlterModelTable(
            name="position",
            table="Position",
        ),
    ]
